### ISSUE TITLE
simplify create-work-transformations.rq

### ISSUE THREAD

**Issue by VladimirAlexiev** [NatLibFi/bib-rdf-pipeline#5]
https://github.com/NatLibFi/bib-rdf-pipeline/blob/master/sparql/create-work-transformations.rq

Isn't this simpler and faster:
```sparql
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>

CONSTRUCT {
  ?s schema:sameAs ?repl .
} WHERE {
  ?s dct:identifier ?key.
  ?repl dct:identifier ?key.
  FILTER (STR(?s) > STR(?repl))
}
```

**Comment by osma** [comment]
Hmm, you're right, but...the idea of the original was to make it transitive, i.e. so that works sharing keys either directly or indirectly would be collapsed. So e.g. if

```
workA hasKey "key1" .
workB hasKey "key1", "key2" .
workC hasKey "key2" .
```

=> A, B and C would all be collapsed into a single work.

Though now I see that the current query isn't doing that (there should probably be a `+` after the path expression).

**Comment by VladimirAlexiev** [comment]
You can close sameAs transitively with a separate query. (Or use a proper repo that supports owl:sameAs :-))

**Comment by osma** [comment]
Sure, inference would be one way (arguably the right way) to do it. But for now I'd like to keep my approach of chaining command line tools into a pipeline. I'm sure the Jena command line tools could be made to perform sameAs inference on a temporary in-memory model, but if the same result can be achieved with a small tweak to the current query (I think I had a working version of that and I've just committed the wrong one), then I'll stick to that.

**Comment by osma** [comment]
The SPARQL query is now transitive (#6). Closing this as it is no longer relevant.
